### ISSUE TITLE
`bias` parameter in `set_benchmarking()`

### ISSUE THREAD

**Issue by AQLT** [rjdemetra/rjd3toolkit#11]
What does the `bias` parameter in the `set_benchmarking()` function correspond to?
It seems that it can takes four values: UNSPECIFIED, NONE, ADDITIVE and MULTIPLICATIVE
https://github.com/rjdemetra/rjd3toolkit/blob/e1d0ab2e46c8379438bdc28eb85037328a17a3b2/inst/proto/sa.proto#L45-L50

**Comment by palatej** [comment]
BENCH_BIAS_UNSPECIFIED is used for unspecified option (only necessary for protocol buffer)
BENCH_BIAS_NONE means no bias correction
For the other options, see the Java code (https://github.com/jdemetra/jdplus-main/blob/develop/jdplus-main-base/jdplus-sa-base-parent/jdplus-sa-base-core/src/main/java/jdplus/sa/base/core/CholetteProcessor.java).
