### ISSUE TITLE
Documentation for rjd3toolkit::dictionary()

### ISSUE THREAD

**Issue by merangelik** [rjdemetra/rjd3toolkit#15]
Hi,

is there some kind of documentation available regarding the output of 
`rjd3toolkit::dictionary()`
or will there be?

This issue is very much related to
https://github.com/rjdemetra/rjd3x13/issues/18
It just concerns a different subpackage of rjd3.

**Comment by TanguyBarthelemy** [comment]
Related to https://github.com/rjdemetra/rjd3x13/issues/18
The function `x13_dictionary` will contain additional descriptions.

**Comment by palatej** [comment]
The "dictionary" function is just an easy way to find all the output generated by the the Java function "getData" (from the interface "jdplus.toolkit.base.api.information.Explorable". That mechanism, which can be extended dynamically, is used to generate output or to retrieve results in a generic (but less efficient) way. It is a low-level function that should probably be renamed as ".dictionary" (and "result" should be renamed ".result").
More specialized dictionaries with documentation are provided for advanced algorithms (x13, tramo-seats...). All the items provided in those dictionaries should be available in "dictionary" (not fully the case for the time being), but "dictionary" can contain other results (for internal purposes for instance), not necessary directly transformed in R structures.
So, "normal" users should always use the specialized and documented dictionaries (in rjd3x13...); the generic "dictionary" is more designed for developers or for "quick and dirty" developments.
