### ISSUE TITLE
Number of parameters of `sarima_estimate()`

### ISSUE THREAD

**Issue by AQLT** [rjdemetra/rjd3toolkit#37]
Is the number of parameters wrongly increased by 1?
For example, with ARIMA(0,0,0)(0,0,0) with no mean, shouldn't the number of parameters be 0?
``` r
rjd3toolkit::sarima_estimate(
    rjd3toolkit::ABS$X0.2.09.10.M,
    order = c(0, 0, 0),
    seasonal = c(0, 0, 0),
    mean = FALSE
)$likelihood
#> Number of observations:  425 
#> Number of effective observations:  425 
#> Number of parameters:  1 
#> 
#> Loglikelihood:  -3620.948 
#> Standard error of the regression (ML estimate):  1213.107 
#> AIC:  7243.897 
#> AICC:  7243.906 
#> BIC:  7247.949
```

**Comment by palatej** [comment]
You have always the variance of the innovations. So, you must indeed add 1.

**Comment by AQLT** [comment]
Ok then I think `logLik.JD3_REGARIMA_RSLTS()` must update (remove the +1 in `df`):
https://github.com/rjdemetra/rjd3toolkit/blob/2a86c874e2b9b3a16f7961b71952d154c0b8f9cf/R/regarima_generic.R#L32
And we should add 1 to `df.residual()`
https://github.com/rjdemetra/rjd3toolkit/blob/2a86c874e2b9b3a16f7961b71952d154c0b8f9cf/R/regarima_generic.R#L60
``` r
y <- AirPassengers
mod_jd <- rjd3toolkit::sarima_estimate(
    y,
    order = c(0, 0, 0),
    seasonal = c(0, 0, 0),
    mean = TRUE
)
mod_r <- arima(y)
mod_lm <- lm(y~1)
logLik(mod_jd)
#> 'log Lik.' -893.1838 (df=3)
logLik(mod_r)
#> 'log Lik.' -893.1838 (df=2)

df.residual(mod_jd)
#> [1] 142
df.residual(mod_lm)
#> [1] 143
```
